# Fabric Properties
	# check these on https://fallen-breath.github.io/fabric-versions/?version=26.1.2
	minecraft_version=26.1.2
	parchment_version=

# Fabric Mod Metadata
	minecraft_dependency=>=26.1 <26.2

# Build Information
	# The target mc versions for the mod during mod publishing, separated with \n
	game_versions=26.1\n26.1.1\n26.1.2

# Dependencies
	# https://masa.dy.fi/maven/fi/dy/masa/malilib/
	# https://jitpack.io/#sakura-ryoko/malilib
	# https://github.com/sakura-ryoko/malilib/releases
	malilib_version = malilib-fabric-26.1.1:0.28.2

	# https://jitpack.io/#sakura-ryoko/litematica
	# https://github.com/sakura-ryoko/litematica/releases
	litematica_file_id = litematica-fabric-26.1.1:0.27.1
