# Fabric Properties
	# check these on https://fallen-breath.github.io/fabric-versions/?version=1.21.10
	minecraft_version=1.21.10
	parchment_version=2025.10.12

# Fabric Mod Metadata
	minecraft_dependency=>=1.21.9 <=1.21.10

# Build Information
	# The target mc versions for the mod during mod publishing, separated with \n
	game_versions=1.21.9\n1.21.10

# Dependencies
	# https://masa.dy.fi/maven/fi/dy/masa/malilib/
	# https://jitpack.io/#sakura-ryoko/malilib
	# https://github.com/sakura-ryoko/malilib/releases
	malilib_version = 1.21.10-0.26.3-sakura.3

	# https://jitpack.io/#sakura-ryoko/litematica
	# https://github.com/sakura-ryoko/litematica/releases
	litematica_file_id = 1.21.10-0.24.2-sakura.2
