# Fabric Properties
	# check these on https://fallen-breath.github.io/fabric-versions/?version=26.3
	minecraft_version=26.3
	parchment_version=

# Fabric Mod Metadata
	minecraft_dependency=>=26.3 <26.4

# Build Information
	# The target mc versions for the mod during mod publishing, separated with newline
	game_versions=26.3

# Dependencies
	# https://masa.dy.fi/maven/fi/dy/masa/malilib/
	# https://jitpack.io/#sakura-ryoko/malilib
	# https://github.com/sakura-ryoko/malilib/releases
	malilib_version = malilib-fabric-26.3:0.30.1

	# https://jitpack.io/#sakura-ryoko/litematica
	# https://github.com/sakura-ryoko/litematica/releases
	litematica_file_id = litematica-fabric-26.3:0.29.0
